image:
  repository: nexus.adsrv.wtf/apps/external-secrets
  tag: main

webhook:
  image:
    repository: nexus.adsrv.wtf/apps/external-secrets
    tag: main

certController:
  image:
    repository: nexus.adsrv.wtf/apps/external-secrets
    tag: main
