image:
  repository: nexus.adsrv.wtf/apps/exteranal-secrets
  tag: main

webhook:
  image:
    repository: nexus.adsrv.wtf/apps/exteranal-secrets
    tag: main

certController:
  image:
    repository: nexus.adsrv.wtf/apps/exteranal-secrets
    tag: main
